services:
  web:
    image: httpd:2.4
    container_name: laravelvue3dev-web
    ports:
      - "8080:80"
      - "443:443"  # HTTPS 포트 매핑
    volumes:
      - ./app/public:/usr/local/apache2/htdocs
      - ./docker/apache/conf:/usr/local/apache2/conf
      - ./certs:/usr/local/apache2/certs:ro
    depends_on:
      - php

  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: laravelvue3dev-php
    volumes:
      - ./app:/var/www/html
    environment:
      - PHP_FPM_CLEAR_ENV=no
    depends_on:
      - db
      - redis

  db:
    image: postgres:16
    container_name: laravelvue3dev-db
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    volumes:
      - ./docker/db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: laravelvue3dev-redis
    ports:
      - "6379:6379"

networks:
  default:
    name: laravelvue3dev-network
